//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsMvcGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenUserGroup
    {
        public System.Guid ID { get; set; }
        public Nullable<int> SlNo { get; set; }
        public System.Guid AppUserID { get; set; }
        public System.Guid GroupID { get; set; }
        public int DataRowVersion { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int IsActive { get; set; }
        public Nullable<long> ChangeSetNumber { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public long CID { get; set; }
    }
}
