//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsMvcGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenUserSessionDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid AppUserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string IPV4Address { get; set; }
        public string IPV6Address { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string MachineName { get; set; }
        public string ADUsername { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<long> ChangeSetNumber { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public Nullable<int> Tmp_ApplicationType { get; set; }
        public long CID { get; set; }
    }
}
